#服务端口
server:
  port: 8088
#日志
logging:
  config: classpath:logback.xml

xxl:
  job:
    #xxl-job管理服务
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    accessToken:
    #执行器配置
    executor:
      appname: xxl-job-executor-demo
      address:
      ip:
      port: 9996
      #执行器执行日志位置，不同执行器可以设置相同位置（日志名由admin管理中心配置）
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30